# name: "primer clase"
# on:
#   push:
#     branches: ["main","master"]

# jobs:
#   deploy-codigofacilito:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: echo "hacemos pull del codigo"
#       - run: echo "correr migraciones"
#       - run: echo "Publicar version"
#       - run: echo "nueva rama3"

name: segunda clase CI deployment server
on:
  push:
    branches: ["master"]
jobs:
  primer_job:
    runs-on: ubuntu-latest

    steps:
      - name: holi
        run: echo "hola mundo"

  segundo_job:
    # configuracino o directiva
    needs: primer_job
    # needs:
    # -primer_job
    # -otro
    # depende del primer job puedo poner mas
    runs-on: ubuntu-latest
    steps:
      - name: holi
        run: echo "segundo trabajo"

  tercer_job:
    if: false
    # el if dice que no corre este
    needs: primer_job
    runs-on: ubuntu-latest
    steps:
      - name: holi
        run: echo "tercer trabajo"

  cuarto_job:
    if: ${{ github.ref == 'refs/heads/master' }}
    # el if dice que no corre este si no es main
    #el contexto se llama github
    # y la variable ref es la rama en la que se esta trabajando

    needs:
      - primer_job
      - segundo_job
    runs-on: ubuntu-latest
    steps:
      - name: holi
        run: echo "cuarto trabajo"

  quinto_job:
    #concatenar con | o &&
    if: ${{ github.ref == 'refs/heads/master' && github.actor == 'DianaDiazDS' }}
    needs:
      - primer_job
      - segundo_job
    runs-on: ubuntu-latest
    steps:
      - name: holi
        run: echo "quinto trabajo"
      - name: holi-bloqueado
        if: false
        run: echo "quinto trabajo-bloqueado cambio luis prueba"

  sexto_job:
    name: "nombre asignado sexto job"
    #concatenar con | o &&
    if: ${{ github.ref == 'refs/heads/master' && github.actor == 'DianaDiazDS' }}
    runs-on: ubuntu-latest

    env:
      VARIABLE: "varible de entrono 2"
      OTRO: "otra variable"
    steps:
      - name: VARIABLES DE ENTORNO
        run: echo "la variable es $VARIABLE y la otra es $OTRO jeje"

  septimo_job:
    name: "acciones"
    runs-on: ubuntu-latest
    steps:
      - name: working dir
        run: ls -al
        # donde esta la direcin actual
      - name: action 
        uses: actions/checkout@v4
        #se pone action/nombre/version
      - name: working dir after action
        run: ls -al
#compartir informacion entre jobs
  octavo_job:
    name: "acciones"
    runs-on: ubuntu-latest
    steps:
      - name: working dir
        id: step_id #para llamar el steps
        run: echo "my_variable_entorno=hola mundo" >> $GITHUB_OUTPUT
      - name: obetener mensaje
        run: echo "el mensaje es ${{ steps.step_id.outputs.my_variable_entorno }}"
      #   run: ls -al
      #   # donde esta la direcin actual
      # - name: action 
      #   uses: actions/checkout@v4
      #   with:
      #     hola: 12
      #   #se pone action/nombre/version
      # - name: working dir after action
      #   run: ls -al 
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
        # donde esta la d
  # diez_job:
  #   needs: tercer_job
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: holi
  #     - uses: actions/checkout@v2
  #     - name: configurar Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '18'
