name: "hola mundo"
on:
  push:
    branches: ["main","master"]

jobs: 
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hacemos pull del codigo"
      - run: echo "correr migraciones"
      - run: echo "Publicar version"
      - run: echo "nueva rama3"
