
name: segunda clase CI deployment server
on:
  push:
    branches: ["master2"]
jobs:
  primer_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        messages: ["Hola mundo", "Hola GitHub Actions", "Hola segunda clase"]
    steps: 
      - name: primer mensaje    
        run: echo "${{ matrix.messages }}"
     #parenteiss se llaman interpolacion  {{}}
  